# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist

class ApiMachineInit(BaseModel):
    """
    ApiMachineInit
    """
    cmd: Optional[conlist(StrictStr)] = None
    entrypoint: Optional[conlist(StrictStr)] = None
    var_exec: Optional[conlist(StrictStr)] = Field(None, alias="exec")
    kernel_args: Optional[conlist(StrictStr)] = None
    swap_size_mb: Optional[StrictInt] = None
    tty: Optional[StrictBool] = None
    __properties = ["cmd", "entrypoint", "exec", "kernel_args", "swap_size_mb", "tty"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiMachineInit:
        """Create an instance of ApiMachineInit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiMachineInit:
        """Create an instance of ApiMachineInit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiMachineInit.parse_obj(obj)

        _obj = ApiMachineInit.parse_obj({
            "cmd": obj.get("cmd"),
            "entrypoint": obj.get("entrypoint"),
            "var_exec": obj.get("exec"),
            "kernel_args": obj.get("kernel_args"),
            "swap_size_mb": obj.get("swap_size_mb"),
            "tty": obj.get("tty")
        })
        return _obj


